extends:
  - semistandard
  - plugin:prettier/recommended
  - prettier/standard
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      bracketSpacing: false
  strict:
    - error
    - safe
overrides:
  - files:
      - wallaby.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.js
    env:
      mocha: true
    globals:
      expect: true
      sinon: true
plugins:
  - prettier
